import type { Metadata } from "next";
import Image from "next/image";
import logo from "@/public/logo.svg";
import arrowR from "@/public/arrow-right-3-svgrepo-com.svg";
import film from "@/public/film-reel-movie-svgrepo-com (1).svg";
import tv from "@/public/screens-modern-variety-svgrepo-com.svg";
import profile from "@/public/profile-1341-svgrepo-com (1).svg";
import HeaderWelcom from "@/app/ui/HeaderWelcom";
import screens from "@/public/1568662-h-a9adef779636.webp";
import movies from "@/public/1568673-h-a49ce1e99d1f.webp";
import tvScreen from "@/public/tv.webp";
import computerScreen from "@/public/computer.webp";
import mobileScreen from "@/public/mobile.webp";
import background from "@/public/home-two-bg.webp";
import Questions from "@/app/components/home/Questions";
import Footer from "@/app/components/home/Footer";
import LoginNavbar from "@/app/components/LoginNavbar";

export const metadata: Metadata = {
  title: "Disney+ | Subscribe Now",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <LoginNavbar />
      <Image
        className="-z-10 bg-cover bg-center object-cover h-[100dvh] max-h-[100dvh]"
        src={background}
        fill
        alt="home background image"
      />
      <main className="w-[98%] md:w-[95%] lg:w-[90%] xl:w-[85%] m-auto max-h-full h-[100dvh] flex flex-col ">
        <div className="flex md:justify-end justify-between items-center pt-4">
          <div className="bg-[#0F1014] text-[#FFFFF0] rounded-md md:pl-6">
            <span className="">Choose language</span>
            <select
              name="languages"
              id=""
              className="bg-[#0F1014] border-none rounded-md focus:outline-none text-lg"
            >
              <option value="english">English</option>
              <option value="arab">العربية</option>
            </select>
          </div>
          <button className="text-white text-lg btn-primary capitalize py-2 px-6 ml-5 ">
            login
          </button>
        </div>
        <div className="flex capitalize z-10 flex-col items-center self-end m-auto w-[95%] md:w-[70%] lg:w-[60%] justify-center ">
          <Image src={logo} alt="disney logo" width={300} height={100} />
          <p className="text-[#E1E6F0] text-3xl max-w-[90%] md:max-w-[70%] leading-relaxed text-center font-bold">
            stream disney+ originals,latest series & blockbuste movies
          </p>
          <button className="text-white group hover:scale-105 transition-transform duration-150 capitalize text-xl btn-primary px-12 py-4 mt-4 flex gap-x-4 items-center">
            sign up now
            <Image
              src={arrowR}
              alt="arrow"
              width={28}
              height={1}
              className="group-hover:translate-x-5 duration-200"
            />
          </button>
        </div>
      </main>
      <section className="m-auto  bg-[#121318]">
        <div className="w-full m-auto h-5/6 grid grid-cols-1 md:grid-cols-2  lg:grid-cols-3 content-center gap-y-4 md:gap-x-3 py-28 bg-[#0F1014] blue-line">
          <div className="info">
            <span>
              <Image src={film} width={40} height={40} alt="film img" />
            </span>
            <p>The Greatest Stories Ever Told</p>
            <h3>
              Disney+ is the streaming home of Disney, Pixar, Marvel, Star Wars,
              National Geographic, plus general entertainment from Star.
            </h3>
          </div>
          <div className="info">
            <span>
              <Image src={tv} width={40} height={40} alt="tv img" />
            </span>
            <p>Experience Disney+ in Arabic</p>
            <h3>
              Thousands of hours of TV series, movies and originals, from all
              the wonderful worlds of Disney+.
            </h3>
          </div>
          <div className="info">
            <span>
              <Image src={profile} width={40} height={40} alt="profile img" />
            </span>
            <p>Easy-to-use parental controls</p>
            <h3>Keep your family safe with our intuitive parental controls.</h3>
          </div>
        </div>
        <div className="w-[95%] m-auto h-fit min-h-[100dvh] flex flex-col items-center justify-center blue-line text-center">
          <div className="w-[95%] m-auto">
            <HeaderWelcom
              header={"Watch the way you want"}
              paragraph={
                "Discover the world's greatest stories,all in one place"
              }
            />
            <Image
              src={screens}
              alt="image"
              className="mt-12 mx-auto"
              width={1200}
              height={1}
              quality={100}
            />
          </div>
          <div className="mt-12 w-[95%] m-auto ">
            <HeaderWelcom
              header={"Exclusive Originals"}
              paragraph={
                "TV series, movies and documentaries you can't see anywhere else, from the world's greatest storytellers."
              }
            />
            <Image
              src={movies}
              alt="image"
              className="mt-12 mx-auto"
              width={1200}
              height={1}
              quality={100}
            />
          </div>
          <div className="mt-20 w-[95%] m-auto ">
            <HeaderWelcom header={"Compatible devices"} />
            <section className="grid grid-cols-1 gap-y-8 md:grid-cols-2 lg:grid-cols-3 w-full content-center md:gap-x-28 lg:gap-x-32 mt-24">
              <div className="flex flex-col items-center justify-start">
                <Image
                  src={tvScreen}
                  alt="tv screen"
                  width={120}
                  height={20}
                  quality={100}
                />
                <h3 className="text-[#E1E6F0] text-2xl font-semibold mt-8">
                  TV
                </h3>
                <ul className="text-[#8F98B2] text-xl mt-4 ">
                  <li>Amazon Fire TV</li>
                  <li className="my-2">Android TV</li>
                  <li className="my-2">AppleTV</li>
                  <li className="my-2">Chromecast</li>
                  <li className="my-2">LG TV</li>
                  <li className="my-2">Samsung</li>
                </ul>
              </div>
              <div className="flex flex-col items-center justify-start">
                <Image
                  src={computerScreen}
                  alt="tv screen"
                  width={140}
                  height={20}
                  quality={100}
                />
                <h3 className="text-[#E1E6F0] text-2xl font-semibold mt-8">
                  Computer
                </h3>
                <ul className="text-[#8F98B2] text-xl mt-4 ">
                  <li>Chrome OS</li>
                  <li className="my-2">MacOS</li>
                  <li className="my-2">Windows PC</li>
                </ul>
              </div>
              <div className="flex flex-col items-center justify-start">
                <Image
                  src={mobileScreen}
                  alt="tv screen"
                  width={50}
                  height={20}
                  quality={100}
                />
                <h3 className="text-[#E1E6F0] text-2xl font-semibold mt-8">
                  Mobile & Tablet
                </h3>
                <ul className="text-[#8F98B2] text-xl mt-4 ">
                  <li>Andriod Phones & Tablets</li>
                  <li className="my-2">iphone and ipad</li>
                </ul>
              </div>
            </section>
          </div>
          <Questions />
        </div>
        <Footer />
      </section>
    </>
  );
}
