import Image from "next/image";
import streamPlatforms from "../../public/cta-logo-one.svg";
import studios from "../../public/cta-logo-two.png";
import background from "@/public/login-background.jpg";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disney+ | login",
  description: "Generated by create next app",
};
const Login = () => {
  return (
    <main className="z-10 h-screen ">
      <Image
        className="-z-10 bg-cover bg-center object-cover h-screen max-h-screen"
        src={background}
        fill
        alt="home background image "
      />
      <section className="flex justify-center text-white items-center w-[45%] content-center m-auto translate-y-[40%]">
        <div className="flex items-center flex-col ">
          <Image
            src={streamPlatforms}
            alt="stream platforms"
            className="w-full"
            width={300}
            height={300}
          />
          <button className="uppercase bg-[#075EE6] hover:bg-[#057EE6] w-full text-center py-4 my-4 rounded-sm">
            get all there
          </button>
          <p className="capitalize text-center max-w-[100%] text-sm text-[#ccc]">
            premier acces to raya and the last dragon for an additional fee with
            a disney+ subscription. as of 03/26/21, the price of disney+ and the
            disney bundle will increase by $1.
          </p>
          <Image src={studios} alt="studios" className="mt-4" />
        </div>
      </section>
    </main>
  );
};

export default Login;
